# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Architecture_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Architecture_MVVM
 pod 'RxFlow'
 pod 'RxSwift'
 pod 'RxRelay'
 pod 'RxCocoa'
 pod 'RxViewController'
 pod 'ReactorKit'
 pod 'Reusable'
 pod 'Moya'
 pod 'SwiftyJSON'
 pod 'Kingfisher'
end
